version: "3.8"

services:
  db:
    image: postgres:13
    container_name: db-todolist
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nextjs-todolist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-todolist
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "npm install && sh src/sequelize/scripts/migrate.sh && npm run dev"
    # command: sh -c "npm install && npm run dev"
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres-data:
